// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("BrandName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<int?>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("BrandID")
                        .HasName("PK__Brands__DAD4F3BE3F51FF50");

                    b.HasIndex("ImageID");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Carrier", b =>
                {
                    b.Property<int>("CarrierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrierID"));

                    b.Property<string>("CarrierName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CarrierID")
                        .HasName("PK__Carriers__CB8205792C7DF4D1");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImagePath")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ImageID")
                        .HasName("PK__Images__7516F4EC329AB438");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<DateOnly?>("LastUpdated")
                        .HasColumnType("date");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("VersionID")
                        .HasColumnType("int");

                    b.Property<int?>("WarehouseID")
                        .HasColumnType("int");

                    b.HasKey("InventoryID")
                        .HasName("PK__Inventor__F5FDE6D389102C7A");

                    b.HasIndex("VersionID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID")
                        .HasName("PK__Orders__C3905BAF7A150433");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID")
                        .HasName("PK__OrderDet__D3B9D30CD8C7DF0B");

                    b.HasIndex("OrderID");

                    b.HasIndex("VersionID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentID")
                        .HasName("PK__Payments__9B556A586FF6760A");

                    b.HasIndex("OrderID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProductID")
                        .HasName("PK__Products__B40CC6ED09C57AB4");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProductDetail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<string>("Battery")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Camera")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Display")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("DetailID")
                        .HasName("PK__ProductD__135C314D12C2A59E");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProductVersion", b =>
                {
                    b.Property<int>("VersionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionID"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("Storage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VersionID")
                        .HasName("PK__ProductV__16C6402FAEE55AB9");

                    b.HasIndex("ImageID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductVersions");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID")
                        .HasName("PK__Reviews__74BC79AE4A396035");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID")
                        .HasName("PK__Roles__8AFACE3A8B8DD55C");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Shipping", b =>
                {
                    b.Property<int>("ShippingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("CarrierID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ShippingID")
                        .HasName("PK__Shipping__5FACD460AF57EDD7");

                    b.HasIndex("CarrierID");

                    b.HasIndex("OrderID");

                    b.ToTable("Shipping", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.SupportTicket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("TicketID")
                        .HasName("PK__SupportT__712CC62719F21F1F");

                    b.HasIndex("UserID");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID")
                        .HasName("PK__Users__1788CCAC7E368D1D");

                    b.HasIndex("RoleID");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534C5E997A7")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Warehouse", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseID"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SurfaceArea")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WarehouseID")
                        .HasName("PK__Warehous__2608AFD9C2EB432A");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Wishlist", b =>
                {
                    b.Property<int>("WishlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistID"));

                    b.Property<DateOnly?>("DateAdded")
                        .HasColumnType("date");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("WishlistID")
                        .HasName("PK__Wishlist__233189CB0E72F674");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("Wishlist", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Brand", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Image", "Image")
                        .WithMany("Brands")
                        .HasForeignKey("ImageID")
                        .HasConstraintName("FK__Brands__ImageID__571DF1D5");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Inventory", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.ProductVersion", "Version")
                        .WithMany("Inventories")
                        .HasForeignKey("VersionID")
                        .HasConstraintName("FK__Inventory__Versi__5812160E");

                    b.HasOne("Infrastructure.Persistence.Entities.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseID")
                        .HasConstraintName("FK__Inventory__Wareh__59063A47");

                    b.Navigation("Version");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Order", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__Orders__UserID__5BE2A6F2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.OrderDetail", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .HasConstraintName("FK__OrderDeta__Order__59FA5E80");

                    b.HasOne("Infrastructure.Persistence.Entities.ProductVersion", "Version")
                        .WithMany("OrderDetails")
                        .HasForeignKey("VersionID")
                        .HasConstraintName("FK__OrderDeta__Versi__5AEE82B9");

                    b.Navigation("Order");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Payment", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderID")
                        .HasConstraintName("FK__Payments__OrderI__5CD6CB2B");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProductDetail", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductID")
                        .HasConstraintName("FK__ProductDe__Produ__5DCAEF64");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProductVersion", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Image", "Image")
                        .WithMany("ProductVersions")
                        .HasForeignKey("ImageID")
                        .HasConstraintName("FK__ProductVe__Image__5FB337D6");

                    b.HasOne("Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("ProductVersions")
                        .HasForeignKey("ProductID")
                        .HasConstraintName("FK__ProductVe__Produ__60A75C0F");

                    b.Navigation("Image");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Review", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .HasConstraintName("FK__Reviews__Product__619B8048");

                    b.HasOne("Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__Reviews__UserID__628FA481");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Shipping", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Carrier", "Carrier")
                        .WithMany("Shippings")
                        .HasForeignKey("CarrierID")
                        .HasConstraintName("FK__Shipping__Carrie__6383C8BA");

                    b.HasOne("Infrastructure.Persistence.Entities.Order", "Order")
                        .WithMany("Shippings")
                        .HasForeignKey("OrderID")
                        .HasConstraintName("FK__Shipping__OrderI__6477ECF3");

                    b.Navigation("Carrier");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.SupportTicket", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__SupportTi__UserI__656C112C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.User", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .HasConstraintName("FK__Users__RoleID__66603565");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Wishlist", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductID")
                        .HasConstraintName("FK__Wishlist__Produc__6754599E");

                    b.HasOne("Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserID")
                        .HasConstraintName("FK__Wishlist__UserID__68487DD7");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Carrier", b =>
                {
                    b.Navigation("Shippings");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Image", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("ProductVersions");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");

                    b.Navigation("Shippings");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Product", b =>
                {
                    b.Navigation("ProductDetails");

                    b.Navigation("ProductVersions");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ProductVersion", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("SupportTickets");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.Warehouse", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
